---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kotosiro.controller.fullname" . }}
  labels: {{- include "kotosiro.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: gossip
      port: 7111
  selector: {{- include "kotosiro.controller.selectorLabels" . | nindent 4 }}


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kotosiro.controller.fullname" . }}
  labels: {{- include "kotosiro.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels: {{- include "kotosiro.controller.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kotosiro.controller.fullname" . }}
  #minReadySeconds: 10
  template:
    metadata:
      labels: {{- include "kotosiro.controller.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: kotosiro
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - controller
          env:
            - name: KOTOSIRO_DB_URL
              value: postgres://postgres:{{ .Values.db.password }}@{{ include "kotosiro.db.fullname" . }}/
            - name: KOTOSIRO_MQ_ADDR
              value: amqp://{{ include "kotosiro.mq.fullname" . }}//
            - name: KOTOSIRO_CONTROLLER_BIND
              value: 0.0.0.0:8080
            - name: KOTOSIRO_CONTROLLER_ADDR
              value: 0.0.0.0:8080
            - name: KOTOSIRO_CLUSTER_GOSSIP_BIND
              value: 0.0.0.0:7111
            - name: KOTOSIRO_CLUSTER_GOSSIP_ADDR
              value: 0.0.0.0:7111
        - name: telegraf
          image: telegraf:latest
          env:
            - name: INFLUX_TOKEN
              value: {{ .Values.metrics.influxToken | b64enc }}
          ports:
            - name: statsd
              containerPort: 8125
              protocol: UDP
          volumeMounts:
            - name: telegraf
              mountPath: /etc/telegraf
              readOnly: true
      volumes:
        - name: telegraf
          configMap:
            name: telegraf
