# Default values for kotosiro.
image:
  registry: ""
  repository: kotosiro
  tag: local
  pullPolicy: IfNotPresent
  pullSecrets: []


# Default values for kotosiro metrics.
metrics:
  influxToken: INFLUX_TOKEN


# Default values for kotosiro controller.
controller:
  replicaCount: 1


# Default values for kotosiro database.
postgres:
  replicaCount: 1
  storageSize: 1G
  proxyPort: 5432
  password: PASSWORD


# Default values for kotosiro message queueing.
rabbitmq:
  replicaCount: 1
  storageSize: 1G
  listenerPort: 5672
  managerPort: 15672
  managerHost: rabbitmq.kotosiro.kube



# Default values for kotosiro service.
service:
  type: ClusterIP
  port: 80

# Default values for kotosiro ingress.
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
