# Default values for kotosiro.
image:
  registry: ""
  repository: kotosiro
  tag: local
  pullPolicy: IfNotPresent
  pullSecrets: []


# Default values for kotosiro metrics.
metrics:
  influxToken: INFLUX_TOKEN


# Default values for kotosiro controller.
controller:
  replicaCount: 1


# Default values for kotosiro database.
db:
  replicaCount: 1
  storageSize: 1G
  internalPort: 5432
  externalPort: 5432
  password: PASSWORD

# Default values for kotosiro service.
service:
  type: ClusterIP
  port: 80

# Default values for kotosiro ingress.
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
