version: "3.9"
services:
  mq:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit consumer_timeout 86400000
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=kotosiro
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
